
seed: 42
checkpoint: true
dataset: microns_classic_feat
num_workers: 4
evaluate_representation: false
model:
  gMHA_type: Hadamard
  gnn_type: GCNConv
  nlayer_gnn: 2
  nlayer_mlpmixer: 2
  hidden_size: 232
  pool: 'mean'
  ctx_as_target_prob: 0.2
train:
  optimizer:
  wd: 0.01
  dropout: 0.2
  mlpmixer_dropout: 0.1
  lr_patience: 20
  epochs: 100
  batch_size: 128
  lr: 0.0001
  runs: 1
  lr_decay: 0.8
  min_lr: 1e-8
metis:
  n_patches: 3
  enable: true
  drop_rate: 0.1
  num_hops: 2

pos_enc:
  rw_dim: 8
  patch_rw_dim: 8
  lap_dim: 8
  patch_num_diff: 0
device: 'cuda'

jepa:
  dist: 1
  enable: true
  num_context: 1  #Что это значит
  num_targets: 1


data:
  root: /home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/JepaAE/data
  knn: 4
  count_per_item: 0
  mode: CopiedGraphs         # RandomPermutate | CopiedGraphs | MarkovGraphs
  gamma: 0.2
  val_ratio: 0.5
  max_patches: 3           
  norm:
    method: zscore
    attr: x

logfile: 
depth : 3